create table if not exists public.products (
  id bigint generated by default as identity primary key,
  product_code text not null unique,
  name text not null,
  category text not null default 'Diğer',
  purchase_price numeric(12,2) not null default 0,
  profit_margin numeric(6,2) not null default 0,
  vat_rate numeric(6,2) not null default 20,
  sale_price numeric(12,2) not null default 0,
  stock integer not null default 0,
  image text,
  brand text default 'Opar',
  vehicle text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
create policy "products public read" on public.products for select using (true);
