'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';

type Product={id:number;product_code:string;product_name:string;product_group:string|null;purchase_price:number;profit_margin:number;vat:number;sale_price:number;stock:number;image_url:string|null};
type FormProduct=Omit<Product,'id'> & {id?:number};
const empty:FormProduct={product_code:'',product_name:'',product_group:'',purchase_price:0,profit_margin:30,vat:20,sale_price:0,stock:0,image_url:null};
const money=(v:number)=>Number(v||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function Page(){
 const [products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(''),[search,setSearch]=useState(''),[form,setForm]=useState<FormProduct|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[page,setPage]=useState(1),[total,setTotal]=useState(0);const pageSize=25;
 async function load(p=page,s=search){setLoading(true);const r=await fetch(`/api/products-list?page=${p}&pageSize=${pageSize}&q=${encodeURIComponent(s)}`,{cache:'no-store'});const x=await r.json();setLoading(false);if(!r.ok){setMessage(x.error||'Ürünler alınamadı.');return}setProducts(x.products);setTotal(x.total)}
 useEffect(()=>{load(1,'')},[]);
 function calculate(next:FormProduct){const sale=Number(next.purchase_price||0)*(1+Number(next.profit_margin||0)/100)*(1+Number(next.vat||0)/100);return {...next,sale_price:Number(sale.toFixed(2))}}
 async function save(){if(!form)return;setMessage('');const editing=Boolean(form.id);const r=await fetch(editing?`/api/products/${form.id}`:'/api/products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const x=await r.json();if(!r.ok){setMessage(x.error||'Kayıt başarısız.');return}setMessage(editing?'Ürün güncellendi.':'Yeni ürün eklendi.');setForm(null);load(page,search)}
 async function remove(p:Product){if(!confirm(`${p.product_name} silinsin mi?`))return;const r=await fetch(`/api/products/${p.id}`,{method:'DELETE'});const x=await r.json();if(!r.ok){setMessage(x.error||'Silme başarısız.');return}setMessage('Ürün silindi.');load(page,search)}
 async function upload(file?:File){if(!file||!form)return;setUploading(true);const fd=new FormData();fd.append('file',file);const r=await fetch('/api/products/upload-image',{method:'POST',body:fd});const x=await r.json();setUploading(false);if(!r.ok){setMessage(x.error||'Görsel yüklenemedi.');return}setForm({...form,image_url:x.image_url})}
 function doSearch(){setPage(1);setSearch(q);load(1,q)}
 const pages=Math.max(1,Math.ceil(total/pageSize));
 return <main style={{maxWidth:1400,margin:'32px auto',padding:'0 18px'}}>
  <p><Link href="/admin">← Yönetim paneli</Link></p>
  <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h1 style={{marginBottom:4}}>Ürün Yönetimi</h1><p style={{marginTop:0,color:'#475569'}}>Toplam {total} ürün</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link href="/admin/excel-yukle" style={btn('#b91c1c')}>Excel Yükle</Link><a href="/api/products/export" style={btn('#334155')}>Dışa Aktar</a><button onClick={()=>setForm({...empty})} style={btn('#047857')}>+ Yeni Ürün</button></div></div>
  <div style={{display:'flex',gap:8,margin:'18px 0'}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&doSearch()} placeholder="Ürün kodu, parça adı veya grup ara" style={{flex:1,padding:12,border:'1px solid #cbd5e1',borderRadius:8}}/><button onClick={doSearch} style={btn('#0f172a')}>Ara</button></div>
  {message&&<p style={{padding:10,background:'#f1f5f9',borderRadius:8}}><b>{message}</b></p>}
  <div style={{overflowX:'auto',border:'1px solid #e2e8f0',borderRadius:10}}><table style={{width:'100%',borderCollapse:'collapse',minWidth:1000}}><thead><tr style={{background:'#f8fafc'}}>{['Görsel','Kod','Parça','Grup','Alış','Satış','Stok','İşlem'].map(h=><th key={h} style={{textAlign:'left',padding:11,borderBottom:'2px solid #e2e8f0'}}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} style={{padding:30,textAlign:'center'}}>Yükleniyor...</td></tr>:products.length===0?<tr><td colSpan={8} style={{padding:30,textAlign:'center'}}>Ürün bulunamadı.</td></tr>:products.map(p=><tr key={p.id} style={{borderBottom:'1px solid #e5e7eb'}}><td style={{padding:8}}>{p.image_url?<img src={p.image_url} alt="" style={{width:54,height:54,objectFit:'contain',border:'1px solid #e5e7eb',borderRadius:6}}/>:<div style={{width:54,height:54,display:'grid',placeItems:'center',background:'#f1f5f9',borderRadius:6,fontSize:11}}>Görsel yok</div>}</td><td style={{padding:9,fontWeight:700}}>{p.product_code}</td><td>{p.product_name}</td><td>{p.product_group||'-'}</td><td>{money(p.purchase_price)} ₺</td><td style={{fontWeight:700}}>{money(p.sale_price)} ₺</td><td>{p.stock}</td><td><button onClick={()=>setForm({...p})}>Düzenle</button> <button onClick={()=>remove(p)} style={{color:'#b91c1c'}}>Sil</button></td></tr>)}</tbody></table></div>
  <div style={{display:'flex',justifyContent:'center',alignItems:'center',gap:12,marginTop:18}}><button disabled={page<=1} onClick={()=>{const n=page-1;setPage(n);load(n,search)}}>← Önceki</button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>{const n=page+1;setPage(n);load(n,search)}}>Sonraki →</button></div>
  {form&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.6)',display:'grid',placeItems:'center',padding:18,zIndex:100}}><div style={{background:'#fff',padding:24,borderRadius:12,width:'min(760px,100%)',maxHeight:'92vh',overflow:'auto'}}><h2>{form.id?'Ürünü Düzenle':'Yeni Ürün Ekle'}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{field('Ürün Kodu','product_code',form,setForm)}{field('Parça Adı','product_name',form,setForm)}{field('Ürün Grubu','product_group',form,setForm)}{numberField('Alış Fiyatı','purchase_price',form,setForm,true)}{numberField('Kar Marjı %','profit_margin',form,setForm,true)}{numberField('KDV %','vat',form,setForm,true)}{numberField('Satış Fiyatı','sale_price',form,setForm,false)}{numberField('Stok','stock',form,setForm,false)}</div><div style={{margin:'14px 0'}}><label><b>Ürün Görseli</b><br/><input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/></label>{uploading&&<span> Yükleniyor...</span>}{form.image_url&&<div><img src={form.image_url} alt="Ürün" style={{marginTop:10,width:140,height:110,objectFit:'contain',border:'1px solid #ddd'}}/></div>}</div><div style={{display:'flex',gap:8}}><button onClick={save} style={btn('#047857')}>Kaydet</button><button onClick={()=>setForm(null)} style={btn('#64748b')}>Vazgeç</button></div></div></div>}
 </main>}
function btn(background:string){return {display:'inline-block',background,color:'#fff',border:0,borderRadius:8,padding:'10px 14px',textDecoration:'none',cursor:'pointer'} as const}
function field(label:string,key:'product_code'|'product_name'|'product_group',form:FormProduct,setForm:(v:FormProduct)=>void){return <label><b>{label}</b><input value={String(form[key]||'')} onChange={e=>setForm({...form,[key]:e.target.value})} style={input}/></label>}
function numberField(label:string,key:'purchase_price'|'profit_margin'|'vat'|'sale_price'|'stock',form:FormProduct,setForm:(v:FormProduct)=>void,recalc:boolean){return <label><b>{label}</b><input type="number" step="0.01" value={form[key]} onChange={e=>{const next={...form,[key]:Number(e.target.value)};setForm(recalc?({ ...next, sale_price:Number((Number(next.purchase_price||0)*(1+Number(next.profit_margin||0)/100)*(1+Number(next.vat||0)/100)).toFixed(2)) }):next)}} style={input}/></label>}
const input={display:'block',width:'100%',padding:10,border:'1px solid #cbd5e1',borderRadius:7,marginTop:5} as const;
