'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';

type ProductRow = { productCode:string; name:string; category:string; purchasePrice:number; profitMargin:number; vatRate:number; salePrice:number; stock:number };
const normalize=(v:unknown)=>String(v??'').trim();
const num=(v:unknown)=>{ if(typeof v==='number') return v; let t=normalize(v).replace('%','').replace(/\s/g,''); if(t.includes(',')&&t.includes('.')) t=t.lastIndexOf(',')>t.lastIndexOf('.')?t.replace(/\./g,'').replace(',','.'):t.replace(/,/g,''); else if(t.includes(',')) t=t.replace(',','.'); const n=Number(t); return Number.isFinite(n)?n:0; };
const get=(row:Record<string,unknown>,names:string[])=>{const keys=Object.keys(row); const exact=keys.find(k=>names.includes(k.toLocaleLowerCase('tr-TR').trim())); if(exact)return row[exact]; const found=keys.find(k=>names.some(n=>k.toLocaleLowerCase('tr-TR').includes(n))); return found?row[found]:undefined;};
export default function Page(){
 const [rows,setRows]=useState<ProductRow[]>([]),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[fileName,setFileName]=useState('');
 const invalid=useMemo(()=>rows.filter(r=>!r.productCode||!r.name||r.salePrice<=0),[rows]);
 async function readFile(file:File){setMessage('');setFileName(file.name);const wb=XLSX.read(await file.arrayBuffer());const sheet=wb.Sheets[wb.SheetNames[0]];const src=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''});setRows(src.map(row=>{const purchasePrice=num(get(row,['alış','alis','purchase']));const profitMargin=num(get(row,['kar marjı','kar marj','kâr marjı','profit']));const vatRate=num(get(row,['kdv','vat']))||20;const imported=num(get(row,['satış rakamı kdv dahil','satış fiyatı kdv dahil','sale price']));return{productCode:normalize(get(row,['ürün kodu','urun kodu','product code','oem'])),name:normalize(get(row,['parça adı','parca adi','ürün adı','urun adi','name'])),category:normalize(get(row,['ürün grubu','urun grubu','kategori','category']))||'Diğer',purchasePrice,profitMargin,vatRate,salePrice:Number((imported||purchasePrice*(1+profitMargin/100)*(1+vatRate/100)).toFixed(2)),stock:Math.trunc(num(get(row,['stok','stock'])))}}).filter(r=>r.productCode||r.name));}
 async function upload(){if(!rows.length||invalid.length)return;setLoading(true);setMessage('');try{const r=await fetch('/api/products/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows})});const x=await r.json();if(!r.ok)throw new Error(x.error);setMessage(`İşlem tamamlandı: ${x.created} yeni ürün, ${x.updated} güncelleme. Toplam ${x.total} ürün.`)}catch(e){setMessage(e instanceof Error?e.message:'Yükleme başarısız.')}finally{setLoading(false)}}
 return <main style={{maxWidth:1250,margin:'35px auto',padding:'0 18px'}}><p><Link href="/admin">← Yönetim paneli</Link></p><h1>Excel’den Ürün Yükle</h1><p>Ürün kodu aynıysa güncellenir, yoksa yeni ürün oluşturulur.</p><label style={{display:'block',border:'2px dashed #cbd5e1',borderRadius:14,padding:28,textAlign:'center',cursor:'pointer',marginTop:22}}><b>{fileName||'Excel veya CSV dosyası seç'}</b><input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])}/></label>
 {rows.length>0&&<><div style={{display:'flex',gap:18,flexWrap:'wrap',margin:'20px 0'}}><b>{rows.length} satır bulundu</b><span style={{color:invalid.length?'#b91c1c':'#15803d'}}>{invalid.length?`${invalid.length} hatalı satır`:'Dosya yüklemeye hazır'}</span></div><div style={{overflowX:'auto',maxHeight:480,border:'1px solid #ddd',borderRadius:10}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:14}}><thead style={{position:'sticky',top:0,background:'#111827',color:'#fff'}}><tr>{['Kod','Parça','Grup','Alış','Kar','KDV','Satış','Stok'].map(h=><th key={h} style={{padding:10,textAlign:'left'}}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((r,i)=><tr key={i} style={{borderTop:'1px solid #e5e7eb',background:(!r.productCode||!r.name||r.salePrice<=0)?'#fee2e2':'white'}}><td style={{padding:8}}>{r.productCode}</td><td>{r.name}</td><td>{r.category}</td><td>{r.purchasePrice.toLocaleString('tr-TR')} ₺</td><td>%{r.profitMargin}</td><td>%{r.vatRate}</td><td><b>{r.salePrice.toLocaleString('tr-TR')} ₺</b></td><td>{r.stock}</td></tr>)}</tbody></table></div><button onClick={upload} disabled={loading||invalid.length>0} style={{marginTop:20,padding:'13px 22px',background:'#c9001c',color:'#fff',border:0,borderRadius:8,fontWeight:700,cursor:'pointer',opacity:loading||invalid.length?0.5:1}}>{loading?'Aktarılıyor…':'Onayla ve Siteye Aktar'}</button></>}{message&&<div style={{marginTop:20,padding:16,borderRadius:8,background:message.startsWith('İşlem')?'#dcfce7':'#fee2e2'}}><b>{message}</b></div>}</main>;
}
