export const GRIZZLY_PARTS = [
  { id:"hood", title:"Kaput", mesh:["hood"], group:"dis-govde" },
  { id:"front-bumper", title:"Ön Tampon", mesh:["front_bumper"], group:"on-grup" },
  { id:"rear-bumper", title:"Arka Tampon", mesh:["rear_bumper"], group:"arka-grup" },
  { id:"fender-left", title:"Sol Ön Çamurluk", mesh:["front_fender_left"], group:"dis-govde" },
  { id:"fender-right", title:"Sağ Ön Çamurluk", mesh:["front_fender_right"], group:"dis-govde" },
  { id:"door-fl", title:"Sol Ön Kapı", mesh:["door_front_left"], group:"dis-govde" },
  { id:"door-fr", title:"Sağ Ön Kapı", mesh:["door_front_right"], group:"dis-govde" },
  { id:"door-rl", title:"Sol Arka Kapı", mesh:["door_rear_left"], group:"dis-govde" },
  { id:"door-rr", title:"Sağ Arka Kapı", mesh:["door_rear_right"], group:"dis-govde" },
  { id:"trunk", title:"Bagaj Kapağı", mesh:["trunk"], group:"arka-grup" },
  { id:"headlight-left", title:"Sol Ön Far", mesh:["headlight_left"], group:"on-grup" },
  { id:"headlight-right", title:"Sağ Ön Far", mesh:["headlight_right"], group:"on-grup" },
  { id:"taillight-left", title:"Sol Stop", mesh:["taillight_left"], group:"arka-grup" },
  { id:"taillight-right", title:"Sağ Stop", mesh:["taillight_right"], group:"arka-grup" },
  { id:"radiator", title:"Radyatör", mesh:["mechanical_radiator"], group:"on-grup" },
  { id:"intercooler", title:"Intercooler", mesh:["mechanical_intercooler"], group:"on-grup" },
  { id:"engine", title:"Motor", mesh:["mechanical_engine"], group:"motor" },
  { id:"transmission", title:"Şanzıman", mesh:["mechanical_transmission"], group:"motor" },
];
